from setuptools import setup, find_packages

setup(name='swmeas',
      version='0.0.1',
      description='Tools monitoring seawater CO2, O2 and Temp.',
      url='https://github.com/oscarbranson/swmeas',
      author='Oscar Branson',
      author_email='oscarbranson@gmail.com',
      license='MIT',
      packages=find_packages(),
      keywords=['science', 'chemistry', 'oceanography', 'carbon'],
      classifiers=['Development Status :: 4 - Beta',
                   'Intended Audience :: Science/Research',
                   'Programming Language :: Python :: 2 :: Only',
                   ],
      install_requires=['numpy',
                        'pyserial==2.7',
                        'matplotlib'],
      package_data={'swmeas': ['resources/*']},
      zip_safe=True)
